Weather app: toolbar and settings screen
e-conomic/android-course pull request #14
Opened 2017-03-30 14:08 UTC by jonholmberg

Added a custom toolbar and a settings screen that lets you change the city so that it automatically updates the forecast when you return to the main screen.

Here are a few test id's if you desire (default is Copenhagen: 2618425):
Vejle: 2610613
London: 6058563
Helsinki: 658225
(An entire list can be found [here](http://openweathermap.org/current))

Toolbar features home/up button and menu with settings. It is hidden for the user when scrolling down and shown again when scrolling up.

Settings activity uses a custom delegate that stores the city in the shared preferences.

2017-04-03 09:15 UTC, tudorgk requested changes
Looks good! 👍  I think some changes are need though
 so here's a 🌵  to get you started 😄 .

2017-04-03 09:15 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/java/com/e_conomic/weatherapp/ui/activities/DetailActivity.kt
>          bindForecast(intent.getSerializableExtra(FORECAST_EXTRA_KEY) as Forecast)
What do you think will happen if the cast fails or we don't have a values stored in the bundle for `FORECAST_EXTRA_KEY`?

2017-04-03 09:15 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/java/com/e_conomic/weatherapp/ui/activities/DetailActivity.kt
>          bindForecast(intent.getSerializableExtra(FORECAST_EXTRA_KEY) as Forecast)
_Hint: safe null cast_

2017-04-03 09:15 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/java/com/e_conomic/weatherapp/ui/activities/MainActivity.kt
> +        initToolbar()
How does a new developer know that he has to call `initToolbar` method before anything happens? I strongly encourage you to check out `abstract` classes 👍 .

2017-04-03 09:15 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/java/com/e_conomic/weatherapp/ui/activities/MainActivity.kt
> +        attachToScroll(forecastList)
Same goes for this.

Consider writing an abstract function that expects a recyclerView. And get's called in the `onCreate()` method in the base abstract class

``` kotlin
abstract fun attachedRecyclerView(): RecyclerView
```

2017-04-03 09:15 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/java/com/e_conomic/weatherapp/ui/activities/MainActivity.kt
> +                uiThread {
We had some problems with this in the past in our sales app. Sometimes the activity might be `null` after the async task has been completed. Don't need to change anything yet, but keep in mind that this won't work in all situations. We'll dive into depth when you will be starting coding for our sales app.

2017-04-03 09:15 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/java/com/e_conomic/weatherapp/ui/activities/MainActivity.kt
> +                    forecastList.adapter = ForecastListAdapter(forecastListResult) { forecast ->
Nice touch with the listener block here.

2017-04-03 09:15 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/java/com/e_conomic/weatherapp/ui/utils/ToolbarManager.kt
> +interface ToolbarManager {
IMO this should be transformed into an `abstract class`. Even though you can have implemented methods in Kotlin interfaces, I think this is a wrong approach when considering that we need to initialise the manager in some way..

2017-04-03 09:15 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/res/layout/activity_detail.xml
>      android:paddingRight="@dimen/weather_item_horizontal_spacing"
Why do we have these padding values here? 
![screen shot 2017-04-03 at 11 10 46](https://cloud.githubusercontent.com/assets/4919888/24602688/355a1cc2-185e-11e7-9d49-6b5662774e0a.png)

2017-04-06 10:14 UTC, jonholmberg commented on jlh/WeatherApp/app/src/main/res/layout/activity_detail.xml
>      android:paddingRight="@dimen/weather_item_horizontal_spacing"
For a wonderful inconsistent layout :D No, I will change it haha :)

2017-04-06 10:21 UTC, jonholmberg commented
@tudorgk I changed the `ToolbarManager` to an abstract class `ToolbarAppCompatActivity`. This now calls `initToolbar()` in the `onCreate()` method, but the content view is required so I have to call `setContentView()` before `super.onCreate()` in `MainActivity` and `DetailActivity` which is not so nice. Do you have a suggestion to make this better? I am very curious :) 

Also I didn't call `attachToScroll()` in `ToolbarAppCompatActivity.onCreate()` since it is not always used.

2017-04-06 10:35 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/java/com/e_conomic/weatherapp/ui/activities/DetailActivity.kt
> +        super.onCreate(savedInstanceState)
Hmm maybe we can make this even prettier. Let's assume that we would always call `setContentView()` in `onCreate()`. So what we would actually need here is just the `int` value that represents the respective layout (in this case `R.layout.activity_detail`). If we create an abstract value name let's say `abstract val layoutId: Int` that will be requested as a parameter for `setContentView()`  in the abstract class' `onCreate` method, we can still call `super.onCreate` first. What do you think, does it get too complicated to follow?

2017-04-06 10:35 UTC, tudorgk commented on jlh/WeatherApp/app/src/main/java/com/e_conomic/weatherapp/ui/utils/ToolbarAppCompatActivity.kt
> +        initToolbar()
You would call the `setContentView()` method here with the abstract value as a parameter.

2017-04-06 10:54 UTC, tudorgk approved these changes

2017-04-06 10:55 UTC, merged